import Link from "next/link";
import Layout from "../../components/layout";
import { grammarTopics } from "../../data/grammar-hub";
import { buildBreadcrumbList, SITE_URL } from "../../lib/seo";

const faq=[{q:"Where should I start learning English grammar?",a:"Begin with what grammar means and parts of speech, then study tenses, agreement, articles, and prepositions before moving to transformations and error detection."},{q:"Is this grammar hub useful for placement preparation?",a:"Yes. The explanations and practice focus on sentence correction, verbal ability, error detection, interview communication, and competitive-exam patterns."},{q:"Does each grammar topic include exercises?",a:"Yes. Every topic page contains multiple-choice questions, guided practice, error detection, interview questions, and answers."}];
const schema=[buildBreadcrumbList([{name:"Home",item:"/"},{name:"English Grammar",item:"/grammar"}]),{"@context":"https://schema.org","@type":"CollectionPage",name:"English Grammar Learning Hub",description:"Complete English grammar for placement preparation.",url:`${SITE_URL}/grammar`,hasPart:grammarTopics.map(topic=>({"@type":"Article",name:topic.title,url:`${SITE_URL}/grammar/${topic.slug}`}))},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(item=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))}];
export default function GrammarHub(){return <Layout title="English Grammar for Placement Preparation" description="Complete English grammar learning hub for placements, competitive exams, engineers, and interviews with topic-wise rules, examples, exercises, and error detection." canonicalUrl="/grammar" keywords="English grammar for placements, grammar for competitive exams, grammar for engineers, verbal ability" structuredData={schema} pageClassName="py-3 sm:py-5">
<nav aria-label="Breadcrumb" className="mb-4 flex items-center gap-2 text-xs font-semibold text-slate-500"><Link href="/">Home</Link><span>/</span><Link href="/placement-preparation">Placement Preparation</Link><span>/</span><span className="text-slate-700">English Grammar</span></nav>
<article className="border border-slate-200 bg-white px-5 py-7 sm:px-8"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-portal-700">Placement Preparation</p><h1 className="mt-2 text-3xl font-black text-[#071d49] sm:text-4xl">English Grammar Learning Hub</h1><p className="mt-4 max-w-4xl text-base leading-8 text-slate-700">Build accurate English for placement tests, competitive examinations, interviews, emails, and professional communication. Follow the topics in order if you are beginning, or open a specific lesson for rules, examples, mistakes, exercises, interview questions, and printable notes.</p>
<section className="mt-8 border-t border-slate-200 pt-7"><h2 className="text-2xl font-black text-[#071d49]">Grammar topics</h2><div className="mt-4 divide-y divide-slate-200">{grammarTopics.map((topic,index)=><Link key={topic.slug} href={`/grammar/${topic.slug}`} className="grid gap-2 py-5 hover:bg-slate-50 sm:grid-cols-[48px_1fr_auto] sm:items-start sm:px-3"><span className="text-sm font-black text-slate-400">{String(index+1).padStart(2,"0")}</span><span><span className="text-lg font-extrabold text-[#071d49]">{topic.shortTitle}</span><span className="mt-1 block text-sm leading-6 text-slate-600">{topic.description}</span></span><span className="text-xs font-bold text-orange-700">Open lesson →</span></Link>)}</div></section>
<section className="mt-8 border-t border-slate-200 pt-7"><h2 className="text-2xl font-black text-[#071d49]">How to use this hub</h2><ol className="mt-4 list-decimal space-y-3 pl-5 text-sm leading-7 text-slate-700"><li>Read the introduction and definition to understand the meaning of the topic.</li><li>Study the formulas and rules, then connect each rule with its examples.</li><li>Review common mistakes before attempting the practice questions.</li><li>Use the interview questions to explain rules aloud in your own words.</li><li>Print important lessons as PDF notes for offline revision.</li></ol></section>
<section className="mt-8 border-t border-slate-200 pt-7"><h2 className="text-2xl font-black text-[#071d49]">Frequently asked questions</h2><div className="mt-3 divide-y divide-slate-200">{faq.map(item=><details key={item.q} className="py-4"><summary className="cursor-pointer font-extrabold text-slate-900">{item.q}</summary><p className="mt-2 text-sm leading-7 text-slate-700">{item.a}</p></details>)}</div></section>
</article></Layout>}