import Link from "next/link";
import Layout from "../../components/layout";
import { placementSections } from "../../data/grammar-hub";
import { buildBreadcrumbList, SITE_URL } from "../../lib/seo";

const schema=[buildBreadcrumbList([{name:"Home",item:"/"},{name:"Placement Preparation",item:"/placement-preparation"}]),{"@context":"https://schema.org","@type":"CollectionPage",name:"Placement Preparation for ECE Students",description:"English grammar, aptitude, reasoning, verbal ability, interview, and resume preparation for engineering placements.",url:`${SITE_URL}/placement-preparation`}];
export default function PlacementPreparation(){return <Layout title="Placement Preparation for ECE Students" description="Placement preparation hub for ECE students covering English grammar, aptitude, logical reasoning, verbal ability, interviews, and resume building." canonicalUrl="/placement-preparation" keywords="placement preparation for ECE students, English grammar for placements, aptitude, interview questions, resume for freshers" structuredData={schema} pageClassName="py-3 sm:py-5">
<nav aria-label="Breadcrumb" className="mb-4 flex items-center gap-2 text-xs font-semibold text-slate-500"><Link href="/">Home</Link><span>/</span><span className="text-slate-700">Placement Preparation</span></nav>
<article className="border border-slate-200 bg-white px-5 py-7 sm:px-8"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-portal-700">Career Preparation</p><h1 className="mt-2 text-3xl font-black text-[#071d49] sm:text-4xl">Placement Preparation for ECE Students</h1><p className="mt-4 max-w-4xl text-base leading-8 text-slate-700">Technical knowledge earns attention; communication, aptitude, and interview performance often decide the final result. This hub brings those placement skills together while keeping the examples relevant to engineering students and freshers.</p>
<section className="mt-8 border-t border-slate-200 pt-7"><h2 className="text-2xl font-black text-[#071d49]">Preparation sections</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{placementSections.map(item=><div key={item.title} id={item.title === "Logical Reasoning" ? "logical-reasoning" : undefined} className="border border-slate-200 p-5"><div className="flex items-center justify-between gap-3"><h3 className="text-lg font-extrabold text-[#071d49]">{item.title}</h3>{item.status==="planned"?<span className="text-[9px] font-extrabold uppercase tracking-wider text-amber-700">In development</span>:null}</div><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p><Link href={item.href} className="mt-4 inline-block text-sm font-extrabold text-orange-700 hover:text-orange-600">{item.status==="available"?"Start learning":"View roadmap"} →</Link></div>)}</div></section>
<section id="interview-questions" className="mt-8 scroll-mt-28 border-t border-slate-200 pt-7"><h2 className="text-2xl font-black text-[#071d49]">Interview preparation roadmap</h2><p className="mt-3 text-sm leading-7 text-slate-700">The interview section will combine ECE technical revision with project explanation, HR questions, BEL and DRDO interview experiences, communication practice, and concise answers. Until the dedicated bank is published, revise technical subjects and practise explaining one project, one strength, one failure, and one engineering decision clearly.</p></section>
<section id="resume-building" className="mt-8 scroll-mt-28 border-t border-slate-200 pt-7"><h2 className="text-2xl font-black text-[#071d49]">Resume building roadmap</h2><p className="mt-3 text-sm leading-7 text-slate-700">A fresher’s resume should prioritize contact details, a focused summary, education, relevant skills, two or three defensible projects, internships, achievements, and links. Every listed skill should be supported by a project, course, or example that you can discuss in an interview.</p></section>
</article></Layout>}